name: 更新最新博客文章
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: 更新 README 中的最新博客文章
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 更新博客文章列表
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.xingshuang.xyz/atom.xml"
          comment_tag_name: "BLOG-POST-LIST"
          commit_message: "🤖 自动更新博客文章列表"
          max_post_count: 5
          template: "✨📅 $date - [$title]($url) \n $newline"
          date_format: "yyyy-MM-dd"
